controllers/ClassController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ClassModel;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * ClassController implements the CRUD actions for ClassModel model.
 */
class ClassController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' =>[
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        //user must be authenticated in order to use this actions
                        'allow' => true,
                        'roles' => ['@']  
                    ]   
                ]
            ]
        ];
    }

    /**
     * Lists all ClassModel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ClassModel::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ClassModel model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ClassModel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ClassModel();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ClassModel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ClassModel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ClassModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ClassModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ClassModel::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/DossierController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\web\Response;
use yii\widgets\ActiveForm;

use app\models\UserContent;
use app\models\User;
use app\models\AwarenessContext;
use app\models\Dossier;

class DossierController extends Controller
{

    public function behaviors(){

        return[
            'access' =>[
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        //user must be authenticated in order to use this actions
                        'allow' => true,
                        'roles' => ['@']  
                    ]   
                ]
            ]
        ];
    }

    public function actionNew($class_id){

        $dossier = new Dossier();
        
        $request = Yii::$app->request;

        if($request->isPost){
            //form is filled
            $dossier->load($request->post());
            $dossier->class = $class_id;
             $dossier->creator = Yii::$app->user->getID();
            if($dossier->save()){
                $this->redirect(['dossier/view', 'id'=>$dossier->id]);
            }
        }

        return $this->render('new', ['dossier'=> $dossier]);
    }

     public function actionDelete($id){

        $dossier = Dossier::findOne($id);
        if($dossier){
            $dossier->delete();
            $classID = $dossier->class;

            return $this->redirect(['class/view', 'id'=>$classID]);
        }
        
        throw new \yii\web\NotFoundHttpException();
    }

    public function actionView($id){
        $dossier = Dossier::findOne($id);

        if(!$dossier)
            throw new \yii\web\NotFoundHttpException("Dossier $id not found");

        return $this->render('view', ['dossier'=>$dossier]);
    }

    public function actionNewContent($id, $type= 'audio'){
        //time bookmark
        $a = $b = $c = $d= $e = 0;
        $a = microtime(true);
        ini_set('max_execution_time', '999');
    	ini_set('memory_limit', '128M');

        $content = new UserContent(['scenario' => UserContent::$SCENARIO_CREATE_DOSSIER]);
        $dossier = new Dossier();
        $dossier->id = $id;

        $request = Yii::$app->request;
        if($request ->isPost){

            $content->load($request ->post());
            $content->file = UploadedFile::getInstance($content, 'file');
            $b = microtime(true);
            if($awarenessContextData = Yii::$app->request->post('AwarenessContext'))
    		{
    			$content->awareness_context = new AwarenessContext();
    			$content->awareness_context->load(json_decode($awarenessContextData, true), '');
    		}

            $isValidationRequest = $request->post("ajax") !== null;
    		
    			Yii::$app->response->format = Response::FORMAT_JSON;
    			$messages = ActiveForm::validate($content);
                if(!empty($messages) || $isValidationRequest){
                    return $messages;
                }
            

                $content->creator = Yii::$app->user->getId();
                $c = microtime(true);

                if($content->file != null){
                    $content->type = UserContent::getFileType($content->file->tempName);
                    $internalDir = $dossier->getContentsInternalDirectory();

                    $content->mime_type = FileHelper::getMimeType($content->file->tempName, null, false);
                    $mimeExtensions = FileHelper::getExtensionsByMimeType($content->mime_type);

                    $ext = $content->file->extension;
                    if(!$ext || empty($ext)){
                        $content->file->extension = UserContent::getExtensionFor($content->file->tempName);
                    }

                    $absolutePath;
                    do{
                        $fileName = UserContent::generateRandomFilename($ext);
                        $content->file_path = $internalDir.'/'.$content->type.'/'.$fileName;

                        $absolutePath = Yii::getAlias('@app')."$content->file_path";
                        $exist = file_exists($absolutePath);
                    }while ($exist);
                    $d = microtime(true);
                    if(!$content->file->saveAs($absolutePath)){
                         throw new \yii\web\ServerErrorHttpException("Cannot save content file");
                    }
                    $e = microtime(true);

                    if(!chmod($absolutePath, 0775)){
                        die("chmod failed");
                    };

                }else{
                    $content->type = 'text';
                    $content->mime_type = 'text/plain';
                }
                
                //success
                //save the record now
                if($content->save(FALSE)){
                    
                    //save dossier x content relation
                    $command = Yii::$app->db->createCommand();

                    $command->insert('dossier_content_map',[
                        'dossier'=> $dossier->id,
                        'content'=> $content->id,
                    ])->execute();

                    $e = microtime(true);
                    echo 'e-a: '.($e-$a)."\n";
                    echo 'e-b: '.($e-$b)."\n";
                    echo 'e-c: '.($e-$c)."\n";
                    echo 'e-d: '.($e-$d)."\n";
                    
                    return $this->redirect(['dossier/view', 'id' => $dossier->id]);
                }
            }            


        return $this->render('create-content', [
                'dossier' => $dossier,
    			'model' => $content,
    			'type' => $type
    	]);
    }

    /*
    * get multimedia contents of this dossier in json format
    * given requested media type
    */
    public function actionContents($id,$before_id = null)
    {
        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_JSON;
    
        $dossier = Dossier::findOne($id);
        if(!$dossier){
            throw new \yii\web\NotFoundHttpException("Dossier not found");
        }   
        return $dossier->getContents($before_id);
    }

    public function actionItemTemplate($type)
    {
        return $this->renderPartial('item-template.mst.php', ['type'=>$type]);
    }

     /**
    * @return \yii\db\ActiveQuery
    */
   public function getClass0()
   {
       return $this->hasOne(ClassModel::className(), ['id' => 'class']);
   }
   /**
    * @return \yii\db\ActiveQuery
    */
   public function getDossierContentMaps()
   {
       return $this->hasMany(DossierContentMap::className(), ['dossier' => 'id']);
   }
   /**
    * @return \yii\db\ActiveQuery
    */
   public function getContents()
   {
       return $this->hasMany(UserContent::className(), ['id' => 'content'])->viaTable('dossier_content_map', ['dossier' => 'id']);
   }

}

views/class/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ClassModel */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="class-model-form">

    <?php $form = ActiveForm::begin(); ?>

    

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
    

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/class/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ClassModel */

$this->title = 'Create Class Model';
 $dossierLoadJs = "$.material.init();";
    $this->registerJs($dossierLoadJs);
?>
<br>
<div class="class-model-create well col-lg-12">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/class/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Class Models';
?>
<div class="class-model-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Class Model', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'creator',
            'title',
            'description:ntext',
            'created_at',
            // 'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/class/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ClassModel */

$this->title = 'Update Class Model: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Class Models', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="class-model-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/class/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ClassModel */
$class = $model;
$this->title = $model->title;

\app\assets\ClassAsset::register($this);

?>     
   
    <div class='col-lg-4 '>
        <div class='well'>
            <h3> <i class="material-icons">school</i> <?= $class->title ?></h3>
            <hr>
            <?= $class->description ?>
            <hr>
            <span>created by</span><br>
            <span class='font-weight-bold'><?= $class->getCreator()->getFullName() ?></span>
            <span class='date-time text-muted font-italic created_time' data-time='<?= $class->created_at ?>'></span>
        </div>
    </div>
    
    <div id='dossier-contents-container' class='col-lg-8'>
        <div class='row no-gutters'>
            <div class='col-lg-12 '>  
                <div class='row  well no-gutters'>
                    <div class='col-lg-9 '>
                        <h4 class='align-middle'>Dossier list</h4>
                        <hr>
                    </div>
                    <div class='col-lg-3 text-right'>
                        <!--Add a content button-->
                        <a  href="<?= Url::to(['dossier/new', 'class_id' => $class->id]); ?>"                         
                            class="btn btn-fab btn-primary btn-raised add-content-btn ">
                            <i class="material-icons">add</i>
                        </a>
                    </div>
                </div>                                                
            </div>
            <?php
                $classModelJson = yii\helpers\Json::encode($class);
                $initClassViewerScript = "$.material.init(); var classViewer = new ClassViewer( $classModelJson );";
                $this->registerJs($initClassViewerScript);
            ?>
            
            <div id='dossiers-list' class='col-lg-12'>           
                <script id='dossier-list-template' type='x-tmpl-mustache'>
                {{#dossiers}}
                <div id='dossier_{{id}}' class='row well dossier-item no-gutters' style='padding-bottom: 4px;' data-dossier-id={{id}}>
                        <div class='col-lg-10'>           
                                <h5>
                                    {{#title}}
                                        {{title}}
                                    {{/title}}
                                    {{^title}}
                                        untitled dossier
                                    {{/title}}
                                </h5>
                                
                                <span>by</span>
                                <span class='font-weight-bold'>{{creator.full_name}}</span>
                                <span class='date-time text-muted font-italic' data-time='{{created_at}}'>{{created_at}}</span>
                                <hr>
                                <div class="btn-group" role="group" style='margin-bottom:0px'>
                                    {{#delete}}
                                        <a href='{{delete}}' class="btn btn-secondary btn-xs" style='padding:0px'>
                                            <i class="material-icons">delete</i>
                                        </a>
                                    {{/delete}}
                                </div>
                        </div>
                        <div class='col-lg-2 text-right'>
                            <a href='{{action_view}}' class='btn btn-default btn-sm'>
                                <i class="material-icons">navigate_next</i>
                            </a>
                        </div>
                    </div>
                 {{/dossiers}}
                </script>
            </div>                            
        </div>
        <div id="no-contents"></div>
</div>