controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public $enableCsrfValidation = false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest){
            return $this->render('index');
        }else{
            //redirect to example class
            return $this->redirect(['class/view', 'id'=>1]);
        }
       
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {

        if (!Yii::$app->user->isGuest) {
                return $this->goHome();
        }

        $model = new LoginForm();
        
        
        if ($model->load(Yii::$app->request->post()) && $model->login()  ) {
            // return Yii::$app->user->identity;
            return $this->goBack();
        }
        return $this->render('login',['model'=>$model]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
         return[
            'access' =>[
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        //user must be authenticated in order to use this actions
                        'allow' => true,
                        'actions' =>['new'],
                        'roles' => ['?']  
                    ]   
                ]
            ]
        ];
    }


    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionNew()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if($model->password != $model->passwordConfirmation){
                $model->addError('password', 'Passwords don\'t match');

            }else{
                $model->password_hash =  Yii::$app->getSecurity()->generatePasswordHash($model->password);

                if($model->save(false)){
                    
                    //per adesso registriamo tutti i nuovi utenti come iscritti
                    //alla classe di esempio che ha id=1
                    $classID = 1;
                    //save class x user relation
                    $command = Yii::$app->db->createCommand();

                    $command->insert('class_user_map',[
                        'class'=>  $classID ,
                        'user'=> $model->id,
                    ])->execute();

                    return $this->redirect(['class/view', 'id' => $classID]);
                }
                 //return $this->redirect(['view', 'id' => $model->id]);
            }
           

        } 

        return $this->render('new', [
            'model' => $model,
        ]);     
    }


    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About MOLLY';
?>
<div class="site-about card col-lg-12">
<div class='card-block'>
    <h1><?= Html::encode($this->title) ?></h1>
    <br>
    <style>
        p{text-indent: '1.5em'}
    </style>
    <p>
       L’obiettivo del progetto MOLLY è la realizzazione di una piattaforma informatica per l’apprendimento
        digitale mirata a favorire la partecipazione attiva degli studenti e l’interazione con la
realtà studiata. </p>

<p>
Vuole essere uno strumento didattico che consente agli alunni di muoversi sul territorio per
andare a mappare dei luoghi con fotograﬁe, video, registrazioni audio e documenti testuali.
</p>
<p>
Gli insegnanti avrebbero la facoltà di aprire un nuovo corso (o classe) al quale aggiungerebbero
 gli studenti partecipanti e altri insegnanti collaboratori.
 </p>
 <p>
All’interno del corso potrebbero aggiungere un nuovo tema di mappatura che descriverebbe il luogo e le caratteristiche da stu-
diare. In questo tema ogni studente, oltre agli insegnanti, potrebbe inserire i contenuti da lui
creati afﬁnché siano visibili, commentabili e valutabili dagli altri. L’insieme di questi contenuti
multimediali formerebbe la base su cui gli studenti, insieme agli insegnanti, realizzerebbero un
documento (articolo o report) del luogo studiato che chiameremo dossier.
</p>
<p>
Insegnanti e studenti potrebbero interagire fra loro commentando e recensendo i contenuti
altrui con lo scopo di migliorare la qualità complessiva del dossier. Terminata l’attività un sot-
toinsieme dei contenuti formerebbe il dossier, che potrà essere reso pubblico o meno. Un dossier
pubblicato sarà visibile a chiunque via web.
</p>
<p>
I genitori degli studenti potranno accedere al sistema e visionare il proﬁlo dei loro ﬁgli
osservando i contenuti da loro creati e le valutazioni che hanno ricevuto.
Studenti, genitori e professori potranno comunicare tra loro attraverso un sistema di messag-
gistica.
</p>
<p>
Il target degli studenti a cui è rivolto il progetto è composto da bambini e ragazzi con età
compresa fra i 6 e i 18 anni.
    </p>

</div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Url;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index col-lg-12 text-center">

        
        <a class="btn btn-lg btn-info btn-raised btn-lg" href='<?= Url::to(['site/login']) ?>'>Sign in</a>
        <a class="btn btn-lg btn-danger btn-raised btn-lg" href='<?= Url::to(['user/new']) ?>'>Sign up</a>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
// $this->params['breadcrumbs'][] = $this->title;

 $dossierLoadJs = "$.material.init();";
    $this->registerJs($dossierLoadJs);
?>
<div class="col-lg-8 offset-lg-2">
<div class="site-login well">
    <h4><i class="material-icons">lock</i> <?= Html::encode($this->title) ?></h4>

    <!--<p>Please fill out the following fields to login:</p>-->

    <?php $form = ActiveForm::begin([
        'enableClientValidation' => true,
        'enableAjaxValidation' => false,
        'validateOnSubmit' => false,
        'options' => [
           // 'enctype' => 'multipart/form-data'
        ],
        'fieldConfig' => [
            'options'=>[
              //  'class' =>'input-group'
            ],
            'errorOptions' => ['class' => 'form-control-feedback'],
            'template' => "{label}\n{input}{hint}\n{error}"   
        ],

        'errorCssClass'=> 'has-warning'
    ]
        ); ?>


        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group float-right">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-raised btn-lg', 'name' => 'login-button']) ?>
        </div>
        <div class="clearfix"></div>


    <?php ActiveForm::end(); ?>

</div>
</div>